---
- name: Install Packer
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    dest: "{{ packer_install_dir }}"
    copy: no
    creates: "{{ packer_install_dir }}/packer"

- name: Create Packer templates.
  template:
    src: templates/packer.json.j2
    dest: "{{ beet_home }}/provisioning/{{ item.atlas_username }}-{{ item.atlas_build_name }}.json"
    force: yes
  with_items:
    - "{{ packer_templates }}"
  when: packer_templates is defined
