---
#
# Beetbox VM configuration.
#
# Settigns below related to the Ansible roles from Galaxy.
# Copy any of these settings to the custom config file to override.
#

# Beetbox config.
beet_repo: "{{ lookup('env','BEET_REPO') | default('https://github.com/beetboxvm/beetbox.git',true) }}"
beet_version: "{{ lookup('env','BEET_VERSION') | default('master',true) }}"
beet_home: "{{ lookup('env','BEET_HOME') | default('/beetbox',true) }}"
beet_role_dir: "{{ beet_home }}/provisioning/ansible/roles"
beet_project: drupal
beet_debug: no
beet_domain: "{{ ansible_hostname }}.local"
beet_aliases: []
beet_user: "{{ lookup('env','BEET_USER') | default('vagrant',true) }}"
beet_base: "{{ lookup('env','BEET_BASE') | default('/var/beetbox',true) }}"
beet_root: "{{ beet_base }}"
beet_web: "{{ beet_root }}"
beet_ssh_home: "{{ beet_root }}"
beet_site_name: "Beetbox"
beet_webserver: apache
beet_mysql_user: beetbox
beet_mysql_password: beetbox
beet_mysql_database: "beetbox"
beet_run_tests: no
beet_custom_pre_tasks: "{{ beet_base }}/.beetbox/tasks/pre/*"
beet_custom_post_tasks: "{{ beet_base }}/.beetbox/tasks/post/*"

# Ansible Galaxy roles.
galaxy_roles:
  - name: beetboxvm.backdrop
    repo: https://github.com/beetboxvm/ansible-role-beetbox-backdrop.git
  - name: beetboxvm.cakephp
    repo: https://github.com/beetboxvm/ansible-role-beetbox-cakephp.git
  - name: beetboxvm.concrete5
    repo: https://github.com/beetboxvm/ansible-role-beetbox-concrete5.git
  - name: beetboxvm.kohana
    repo: https://github.com/beetboxvm/ansible-role-beetbox-kohana.git
  - name: beetboxvm.modx
    repo: https://github.com/beetboxvm/ansible-role-beetbox-modx.git
  - name: beetboxvm.silverstripe
    repo: https://github.com/beetboxvm/ansible-role-beetbox-silverstripe.git
  - name: beetboxvm.selenium
    repo: https://github.com/beetboxvm/ansible-role-selenium.git
  - name: beetboxvm.slim
    repo: https://github.com/beetboxvm/ansible-role-beetbox-slim.git
  - name: beetboxvm.wordpress
    repo: https://github.com/beetboxvm/ansible-role-beetbox-wordpress.git
  - name: ANXS.postgresql
    repo: https://github.com/ANXS/postgresql
  - name: franklinkim.newrelic
    repo: https://github.com/weareinteractive/ansible-newrelic.git
  - name: geerlingguy.adminer
    repo: https://github.com/geerlingguy/ansible-role-adminer.git
  - name: geerlingguy.apache
    repo: https://github.com/geerlingguy/ansible-role-apache.git
  - name: geerlingguy.apache-php-fpm
    repo: https://github.com/geerlingguy/ansible-role-apache-php-fpm.git
  - name: geerlingguy.blackfire
    repo: https://github.com/geerlingguy/ansible-role-blackfire.git
  - name: geerlingguy.composer
    repo: https://github.com/geerlingguy/ansible-role-composer.git
  - name: geerlingguy.daemonize
    repo: https://github.com/geerlingguy/ansible-role-daemonize.git
  - name: geerlingguy.drupal-console
    repo: https://github.com/geerlingguy/ansible-role-drupal-console.git
  - name: geerlingguy.drush
    repo: https://github.com/geerlingguy/ansible-role-drush.git
  - name: geerlingguy.firewall
    repo: https://github.com/geerlingguy/ansible-role-firewall.git
  - name: geerlingguy.git
    repo: https://github.com/geerlingguy/ansible-role-git.git
  - name: geerlingguy.java
    repo: https://github.com/geerlingguy/ansible-role-java.git
  - name: geerlingguy.mailhog
    repo: https://github.com/geerlingguy/ansible-role-mailhog.git
  - name: geerlingguy.memcached
    repo: https://github.com/geerlingguy/ansible-role-memcached.git
  - name: geerlingguy.mysql
    repo: https://github.com/geerlingguy/ansible-role-mysql.git
  - name: geerlingguy.nginx
    repo: https://github.com/geerlingguy/ansible-role-nginx.git
  - name: geerlingguy.nodejs
    repo: https://github.com/geerlingguy/ansible-role-nodejs.git
  - name: geerlingguy.php
    repo: https://github.com/geerlingguy/ansible-role-php.git
  - name: geerlingguy.php-memcached
    repo: https://github.com/geerlingguy/ansible-role-php-memcached.git
  - name: geerlingguy.php-mysql
    repo: https://github.com/geerlingguy/ansible-role-php-mysql.git
  - name: geerlingguy.php-pecl
    repo: https://github.com/geerlingguy/ansible-role-php-pecl.git
  - name: geerlingguy.php-redis
    repo: https://github.com/geerlingguy/ansible-role-php-redis.git
  - name: geerlingguy.php-xdebug
    repo: https://github.com/geerlingguy/ansible-role-php-xdebug.git
  - name: geerlingguy.php-xhprof
    repo: https://github.com/geerlingguy/ansible-role-php-xhprof.git
  - name: geerlingguy.pimpmylog
    repo: https://github.com/geerlingguy/ansible-role-pimpmylog.git
  - name: geerlingguy.postfix
    repo: https://github.com/geerlingguy/ansible-role-postfix.git
  - name: geerlingguy.redis
    repo: https://github.com/geerlingguy/ansible-role-redis.git
  - name: geerlingguy.ruby
    repo: https://github.com/geerlingguy/ansible-role-ruby.git
  - name: geerlingguy.security
    repo: https://github.com/geerlingguy/ansible-role-security.git
  - name: geerlingguy.solr
    repo: https://github.com/geerlingguy/ansible-role-solr.git
  - name: geerlingguy.varnish
    repo: https://github.com/geerlingguy/ansible-role-varnish.git
  - name: hashbangcode.pantheon-cli
    repo: https://github.com/hashbangcode/ansible-role-pantheon-cli.git
  - name: heskethm.wp-cli
    repo: https://github.com/heskethm/ansible-role-wp-cli.git
  - name: pwelch.avahi
    repo: https://github.com/pwelch/ansible-avahi.git

# Symlinks.
symlinks: no

# Known hosts.
known_hosts: no

# Apache config.
apache_daemon: apache2
apache_remove_default_vhost: true
apache_listen_port: "{{ (beet_webserver == 'apache') | ternary('80','82') }}"
apache_vhosts:
  - servername: "{{ beet_domain }}"
    documentroot: "{{ beet_web }}"
apache_listen_port_ssl: "{{ (beet_webserver == 'apache') | ternary('443','444') }}"
apache_vhosts_ssl:
  - servername: "{{ beet_domain }}"
    documentroot: "{{ beet_web }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
apache_mods_enabled:
  - authn_core.load
  - expires.load
  - ssl.load
  - rewrite.load

# Databases.
mysql_databases:
  - name: "{{ beet_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ beet_mysql_user }}"
    host: "%"
    password: "{{ beet_mysql_password }}"
    priv: "*.*:ALL"

# Extra utilities form provided roles.
# Enabled by default.
installed_extras_adminer: yes
installed_extras_mailhog: yes
installed_extras_memcached: yes
installed_extras_xdebug: yes
installed_extras_xhprof: yes
installed_extras_selenium: yes
installed_extras_drupal_console: yes
installed_extras_drush: yes
installed_extras_upload_progress: yes

# Disabled by default.
installed_extras_firewall: no
installed_extras_postfix: no
installed_extras_pantheon_cli: no
installed_extras_varnish: no
installed_extras_pimpmylog: no
installed_extras_postgresql: no
installed_extras_nodejs: no
installed_extras_ruby: no
installed_extras_solr: no
installed_extras_redis: no
installed_extras_blackfire: no
installed_extras_newrelic: no
installed_extras_wp_cli: no

# Extra packages.
extra_packages:
  - imagemagick
  - php5-sqlite
  - unzip

# git config.
git_packages:
  - git

# Varnish config.
varnish_listen_port: 81
varnish_storage: "malloc,256m"

# Nodejs config.
nodejs_version: "0.12"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "{{ beet_user }}"

# Ruby config.
ruby_install_gems_user: "vagrant"
ruby_install_gems: []

# Nginx config.
nginx_listen_port: "{{ (beet_webserver == 'nginx') | ternary('80','82') }}"
nginx_php_fpm: /var/run/php5-fpm.sock
nginx_remove_default_vhost: true
nginx_hosts:
  - listen: "{{ nginx_listen_port }}"
    server_name: "{{ beet_domain }}"
    root: "{{ beet_web }}"
    is_php: true

# PHP config.
php_version: "5.6"
php_memory_limit: "192M"
php_date_timezone: "Australia/Melbourne"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_enable_apc: no
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_opcache_conf_filename: "10-opcache.ini"
php_max_input_vars: "4000"
php_conf_paths:
  - "/etc/php/{{ php_version }}/fpm"
  - "/etc/php/{{ php_version }}/apache2"
  - "/etc/php/{{ php_version }}/cli"
php_extension_conf_paths:
  - "/etc/php/{{ php_version }}/fpm/conf.d"
  - "/etc/php/{{ php_version }}/apache2/conf.d"
  - "/etc/php/{{ php_version }}/cli/conf.d"
php_fpm_daemon: "php{{ php_version }}-fpm"
php_fpm_conf_path: "/etc/php/{{ php_version }}/fpm"
php_fpm_pool_conf_path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
php_mysql_package: "php{{ php_version }}-mysql"
php_memcached_package: "php-memcache"
php55_packages:
  - php5.5
  - php5.5-curl
  - php5.5-dev
  - php5.5-fpm
  - php5.5-gd
  - php5.5-intl
  - php5.5-mbstring
  - php5.5-xml
  - libapache2-mod-php5.5
php56_packages:
  - php5.6
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-intl
  - php5.6-json
  - php5.6-mbstring
  - php5.6-mysql
  - php5.6-opcache
  - php5.6-readline
  - php5.6-xml
  - libapache2-mod-php5.6
php70_packages:
  - php7.0
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-sqlite3
  - php7.0-xml
  - libapache2-mod-php7.0

# Composer config.
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
composer_home_owner: "{{ beet_user }}"
composer_home_group: "{{ beet_user }}"
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# NodeJS Configuration.
npm_config_prefix: "~/.npm-global"

# Drush config.
drush_version: "8.1.2"
drush_keep_updated: "{{ (drush_version != '8.1.2') }}"
drush_composer_cli_options: "--prefer-dist --no-interaction"

# MySQL config.
mysql_root_password: ""
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug config.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_max_nesting_level: 256
# IDE key for debug.
php_xdebug_idekey: PHPSTORM
# php_xdebug_idekey: sublime.xdebug

# Xhprof config.
xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master

# Solr config.
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium config.
selenium_version: 2.46.0

# Mailhog.
mailhog_daemonize_bin_path: /usr/sbin/daemonize

# Other config.
known_hosts_path: ~/.ssh/known_hosts
workspace: "{{ beet_home }}/workspace/{{ php_version }}"

# Packer config.
packer_templates:
  - atlas_username: beet
    atlas_build_name: dev
    box_version: "0.2.{{ lookup('env','CIRCLE_BUILD_NUM') | default('0',true) }}"
    beet_version: master
    ssh_name: vagrant
    ssh_pass: vagrant
    hostname: "beetbox.local"
    iso_url: "http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso"
    iso_checksum: "07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a"
  - atlas_username: beet
    atlas_build_name: box
    box_version: "{{ lookup('env','CIRCLE_TAG') | default('0.1.1',true) }}"
    beet_version: "{{ lookup('env','CIRCLE_TAG') | default('0.1.1',true) }}"
    ssh_name: vagrant
    ssh_pass: vagrant
    hostname: "beetbox.local"
    iso_url: "http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso"
    iso_checksum: "07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a"
