---
#
# Default Beetbox VM configuration.
#
# Settings below related to the Ansible roles from Galaxy.
# Copy any of these settings to the custom config file to override.
#

# Beetbox config.
beet_repo: "{{ lookup('env','BEET_REPO') | default('https://github.com/beetboxvm/beetbox.git',true) }}"
beet_version: "{{ lookup('env','BEET_VERSION') | default('master',true) }}"
beet_home: "{{ lookup('env','BEET_HOME') | default('/beetbox',true) }}"
beet_role_dir: "{{ beet_home }}/provisioning/ansible/roles"
beet_project: drupal
beet_debug: no
beet_domain: "{{ ansible_hostname }}.local"
beet_aliases: []
beet_env_name: BB_ENVIRONMENT
beet_env: vagrant
beet_user: "{{ lookup('env','BEET_USER') | default('vagrant',true) }}"
beet_base: "{{ lookup('env','BEET_BASE') | default('/var/beetbox',true) }}"
beet_root: "{{ beet_base }}"
beet_web: "{{ beet_root }}"
beet_ssh_home: "{{ beet_root }}"
beet_site_name: "Beetbox"
beet_webserver: apache
beet_mysql_user: beetbox
beet_mysql_password: beetbox
beet_mysql_database: "beetbox"
beet_custom_pre_tasks: "{{ beet_base }}/.beetbox/tasks/pre/*"
beet_custom_post_tasks: "{{ beet_base }}/.beetbox/tasks/post/*"
beet_root_create: yes
beet_provision: yes

# Symlinks.
symlinks: no

# Known hosts.
known_hosts: no

# Apache config.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>
    SetEnv {{ beet_env_name }} {{ beet_env }}
apache_daemon: apache2
apache_remove_default_vhost: true
apache_listen_port: "{{ (beet_webserver == 'apache') | ternary('80','82') }}"
apache_vhosts:
  - servername: "{{ beet_domain }}"
    documentroot: "{{ beet_web }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
apache_listen_port_ssl: "{{ (beet_webserver == 'apache') | ternary('443','444') }}"
apache_vhosts_ssl:
  - servername: "{{ beet_domain }}"
    documentroot: "{{ beet_web }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
apache_mods_enabled:
  - authn_core.load
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Databases.
mysql_databases:
  - name: "{{ beet_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ beet_mysql_user }}"
    host: "%"
    password: "{{ beet_mysql_password }}"
    priv: "*.*:ALL"

# Condintional roles.
installed_extras_init: no
installed_extras_adminer: no
installed_extras_apache: no
installed_extras_apparmor: no
installed_extras_avahi: no
installed_extras_composer: no
installed_extras_drupal_console: no
installed_extras_drush: no
installed_extras_git: no
installed_extras_mailhog: no
installed_extras_memcached: no
installed_extras_mysql: no
installed_extras_nginx: no
installed_extras_pecl: no
installed_extras_php: no
installed_extras_upload_progress: no
installed_extras_web: no
installed_extras_xdebug: no
installed_extras_xhprof: no
installed_extras_lxd: no
installed_extras_selenium: no
installed_extras_elasticsearch: no
installed_extras_firewall: no
installed_extras_postfix: no
installed_extras_pantheon_cli: no
installed_extras_varnish: no
installed_extras_pimpmylog: no
installed_extras_postgresql: no
installed_extras_nodejs: no
installed_extras_ruby: no
installed_extras_rvm: no
installed_extras_solr: no
installed_extras_redis: no
installed_extras_blackfire: no
installed_extras_newrelic: no
installed_extras_wp_cli: no
installed_extras_phantomjs: no
installed_extras_dcr: no

# apt repositories.
apt_repos:
  - ppa:ondrej/apache2
  - ppa:ondrej/php

# Extra packages.
extra_packages:
  - imagemagick
  - php5-sqlite
  - unzip

# git config.
git_packages:
  - git

# Varnish config.
varnish_listen_port: 81
varnish_storage: "malloc,256m"

# Nodejs config.
nodejs_version: "4.x"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "{{ beet_user }}"
npm_config_prefix: "/home/{{ beet_user }}/.npm-global"

# Ruby config.
ruby_install_gems_user: "vagrant"
ruby_install_gems: []

# Nginx config.
nginx_listen_port: "{{ (beet_webserver == 'nginx') | ternary('80','82') }}"
nginx_php_fpm: /var/run/php5-fpm.sock
nginx_remove_default_vhost: true
nginx_hosts:
  - listen: "{{ nginx_listen_port }}"
    server_name: "{{ beet_domain }}"
    root: "{{ beet_web }}"
    is_php: true

# Docker config.
docker_group_members:
  - "{{ beet_user }}"

# PHP config.
php_version: "5.6"
php_memory_limit: "192M"
php_date_timezone: "Australia/Melbourne"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_enable_apc: no
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_opcache_conf_filename: "10-opcache.ini"
php_max_input_vars: "4000"
php_conf_paths:
  - "/etc/php/{{ php_version }}/fpm"
  - "/etc/php/{{ php_version }}/apache2"
  - "/etc/php/{{ php_version }}/cli"
php_extension_conf_paths:
  - "/etc/php/{{ php_version }}/fpm/conf.d"
  - "/etc/php/{{ php_version }}/apache2/conf.d"
  - "/etc/php/{{ php_version }}/cli/conf.d"
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
php_fpm_daemon: "php{{ php_version }}-fpm"
php_fpm_conf_path: "/etc/php/{{ php_version }}/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"
php_mysql_package: "php{{ php_version }}-mysql"
php_memcached_package: "php-memcache"
php_install_recommends: no
php_module_path: "/usr/lib/php{{ php_version }}/modules"
php55_packages:
  - php5.5
  - php5.5-curl
  - php5.5-dev
  - php5.5-fpm
  - php5.5-gd
  - php5.5-intl
  - php5.5-mbstring
  - php5.5-xml
  - libapache2-mod-php5.5
php56_packages:
  - php5.6
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-intl
  - php5.6-json
  - php5.6-mcrypt
  - php5.6-mbstring
  - php5.6-mysql
  - php5.6-opcache
  - php5.6-readline
  - php5.6-xml
  - php5.6-zip
  - libapache2-mod-php5.6
php70_packages:
  - php7.0
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-sqlite3
  - php7.0-xml
  - libapache2-mod-php7.0

# Composer config.
composer_path: /usr/bin/composer
composer_home_path: '/home/{{ beet_user }}/.composer'
composer_home_owner: "{{ beet_user }}"
composer_home_group: "{{ beet_user }}"
composer_global_packages:
  - name: hirak/prestissimo
    release: '^0.3'

# Drush config.
drush_version: "8.x"
drush_clone_depth: ~
drush_keep_updated: "{{ (drush_version != '8.x') }}"
drush_create_alias: yes
drush_alias_name: "{{ beet_domain }}"

# MySQL config.
mysql_port: "3306"
mysql_root_password: ""
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug config.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_max_nesting_level: 256
# IDE key for debug.
php_xdebug_idekey: PHPSTORM
# php_xdebug_idekey: sublime.xdebug
php_xdebug_module_path: "{{ php_module_path }}"

# Xhprof config.
xhprof_download_url: https://github.com/phacility/xhprof/archive/master.tar.gz
xhprof_download_folder_name: xhprof-master
php_xhprof_module_path: "{{ php_module_path }}"

# uploadprogress config.
php_uploadprogress_module_path: "{{ php_module_path }}"

# Solr config.
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium config.
selenium_version: 2.46.0

# Mailhog.
mailhog_daemonize_bin_path: /usr/sbin/daemonize

# DCR config.
dcr_install_dir: "{{ beet_root }}"

# Other config.
known_hosts_path: ~/.ssh/known_hosts
workspace: "{{ beet_home }}/workspace/{{ php_version }}"
welcome_template: "templates/welcome.txt.j2"

# Packer config.
packer_templates:
  - atlas_username: beet
    atlas_build_name: dev
    box_version: "0.4.{{ lookup('env','CIRCLE_BUILD_NUM') | default('0',true) }}"
    beet_version: master
    ssh_name: vagrant
    ssh_pass: vagrant
    hostname: "beetbox.local"
    iso_url: "http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso"
    iso_checksum: "07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a"
  - atlas_username: beet
    atlas_build_name: box
    box_version: "{{ lookup('env','CIRCLE_TAG') | default('0.1.1',true) }}"
    beet_version: "{{ lookup('env','CIRCLE_TAG') | default('0.1.1',true) }}"
    ssh_name: vagrant
    ssh_pass: vagrant
    hostname: "beetbox.local"
    iso_url: "http://releases.ubuntu.com/trusty/ubuntu-14.04.4-server-amd64.iso"
    iso_checksum: "07e4bb5569814eab41fafac882ba127893e3ff0bdb7ec931c9b2d040e3e94e7a"
