---
- name: Check if Silverstripe is already set up.
  stat: "path={{ beet_root }}/index.php"
  register: ss_site

- name: Create new Silverstripe project
  command: >
    {{ composer_path }} create-project silverstripe/installer {{ beet_root }} {{ ss_version }}
  notify: restart webserver
  when: ss_create_project and not ss_site.stat.exists
  sudo: no

- name: Copy the Silverstripe config file.
  template:
    src: _ss_environment.php.j2
    dest: "{{ beet_root }}/_ss_environment.php"
  notify: restart webserver
  when: ss_install_site

- name: Check if Silverstripe sake is available.
  stat: "path={{ beet_root }}{{ ss_sake_path }}"
  register: ss_sake

- name: Copy sake to a globally-accessible location.
  copy:
    src: "{{ beet_root }}{{ ss_sake_path }}"
    dest: /usr/bin/sake
    mode: 0755
  when: ss_sake.stat.exists
