---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - config/beetbox.config.yml
    - config/project.config.yml
    - config/vagrant.config.yml
    - config/local.config.yml

  vars:
    beet_update: no

  tasks:

    - name: Create {{ beet_user }} user.
      user:
        name: "{{ beet_user }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ beet_user }}"

    - name: Ensure admin group exists.
      group:
        name: admin
        state: present

    - name: "Ensure {{ beet_user }} user is in admin group."
      user:
        name: "{{ beet_user }}"
        append: yes
        groups: "admin"

    - set_fact:
        beet_update: yes
      when: "{{ beet_repo != 'https://github.com/beetboxvm/beetbox.git' }}"

    - set_fact:
        beet_update: yes
      when: "{{ beet_version != 'master' }}"

    - set_fact:
        beet_update: no
      when: beet_debug

    - name: Check for updates.
      git:
        repo: "{{ beet_repo }}"
        dest: "{{ beet_home }}"
        version: "{{ beet_version }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: beet_update

    - name: Set ownership of beet_home directory.
      file:
        path: "{{ beet_home }}"
        owner: "{{ beet_user }}"
        group: "{{ beet_user }}"
        recurse: yes
        state: directory
      failed_when: false

    - name: Set ownership of beet_base directory.
      file:
        path: "{{ beet_base }}"
        owner: "{{ beet_user }}"
        group: "{{ beet_user }}"
        state: directory
      failed_when: false
