---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - beetbox.config.yml
    - project.config.yml
    - vagrant.config.yml
    - local.config.yml

  vars:
    beet_update: no

  tasks:

    - name: Create {{ beet_user }} user.
      user:
        name: "{{ beet_user }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ beet_user }}"

    - set_fact:
        beet_update: yes
      when: "{{ beet_repo != 'https://github.com/DrupalMel/beetbox.git' }}"

    - set_fact:
        beet_update: yes
      when: "{{ beet_version != 'master' }}"

    - set_fact:
        beet_update: no
      when: beet_debug

    - name: Check for updates.
      git:
        repo: "{{ beet_repo }}"
        dest: "{{ beet_home }}"
        version: "{{ beet_version }}"
        accept_hostkey: yes
        update: yes
        force: yes
      when: beet_update

    - name: Set ownership of beet_home directory.
      file:
        path: "{{ beet_home }}"
        owner: "{{ beet_user }}"
        group: "{{ beet_user }}"
        recurse: yes
        state: directory
      failed_when: false

    - name: Set ownership of beet_base directory.
      file:
        path: "{{ beet_base }}"
        owner: "{{ beet_user }}"
        group: "{{ beet_user }}"
        state: directory
      failed_when: false
