---
#
# Docker profile.
#

# Enabled roles.
installed_extras_init: yes
installed_extras_apache: yes
installed_extras_avahi: yes
installed_extras_composer: yes
installed_extras_git: yes
installed_extras_mailhog: yes
installed_extras_nginx: yes
installed_extras_php: yes
installed_extras_upload_progress: yes
installed_extras_web: yes

# Extra packages.
extra_packages:
  - imagemagick
  - mysql-client
  - php5-sqlite
  - unzip
