---
# Vagrant config.
vagrant_ip: 192.168.88.88
vagrant_memory: 1024
vagrant_cpus: 2

# Beetbox settings.
beet_project: drupal
beet_domain: "beetbox.local"
beet_root: "{{ beet_base }}/projects/{{ beet_project }}"
beet_mysql_database: "beetbox_{{ beet_project }}"
beet_site_name: "Beetbox"

# Drupal settings.
drupal_build_makefile: yes
drupal_makefile_path: "{{ beet_base }}/drupal8.make.yml"
drupal_install_site: yes
drupal_account_name: admin
drupal_account_pass: admin

# Beetbox debug.
beet_debug: no

# Beetbox tests.
beet_run_tests: yes

#
# Examples.
#

# Backdrop.
#beet_project: backdrop
#backdrop_checkout: yes
#backdrop_version: "1.2.2"
#backdrop_install_site: yes
#backdrop_account_name: admin
#backdrop_account_pass: admin

# CakePHP.
#beet_project: cakephp
#cake_create_project: yes
#beet_mysql_database: "my_app"
#beet_mysql_user: "my_app"
#beet_mysql_password: "secret"

# Concrete5.
#beet_project: concrete5
#beet_web: "{{ beet_root }}/web"
#c5_checkout: yes
#c5_version: "5.7.5.3"
#c5_install: yes
#c5_admin_mail: "admin@example.com"
#c5_admin_password: password
#php_short_open_tag: yes

# Drupal composer.
#beet_root: "/www/projects/{{ beet_project }}-composer"
#beet_web: "{{ beet_root }}/web"
#drupal_build_makefile: no
#drupal_build_composer: yes
#drupal_account_name: admin
#drupal_account_pass: admin

# Kohana.
#beet_project: kohana
#kohana_checkout: yes
#kohana_version: "v3.3.4"
#kohana_configure: yes
#kohana_remove_install: yes

# Modx.
#beet_project: modx
#modx_checkout: yes
#modx_version: "2.x"
#modx_install_site: yes
#modx_account_name: admin
#modx_account_pass: admin

# Silverstripe.
#beet_project: silverstripe
#ss_create_project: yes
#ss_install_site: yes
#ss_account_name: admin
#ss_account_pass: admin

# Slim.
#beet_project: slim
#slim_create_new: yes
#slim_add_example: yes
#slim_add_htaccess: yes

# WordPress.
#beet_project: wordpress
#wp_download_core: yes
#wp_install_site: yes
#wp_account_name: admin
#wp_account_pass: admin
#wp_account_email: "admin@beetbox.local"
