---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Get software for Python-based control.
  apt: "name={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - build-essential

- name: Disable the ufw firewall (since we use a simple iptables firewall).
  service: name=ufw state=stopped
  failed_when: false

- set_fact: php_ppa=ppa:ondrej/php5
  when: php_version == '5.5'

- set_fact: php_ppa=ppa:ondrej/php5-5.6
  when: php_version == '5.6'

- set_fact: php_ppa=ppa:ondrej/php-7.0
  when: php_version == '7.0'

- name: Add repository for PHP.
  apt_repository: repo="{{ php_ppa }}"
  register: php_repository

- name: Purge repository for PHP.
  apt_repository: "repo={{ item }} state=absent"
  when: "php_ppa != item and php_repository.changed"
  with_items:
    - ppa:ondrej/php5
    - ppa:ondrej/php5-5.6
    - ppa:ondrej/php-7.0

- name: Purge php packages.
  apt: name={{ item }} state=absent
  when: php_repository.changed
  with_items: php_packages

- name: Ensure beet_root directory exists.
  file:
    path: "{{ beet_root }}"
    state: directory
    mode: 0775
  become: no
  when: beet_root is defined

- name: Set SSH home directory.
  lineinfile:
    dest: /home/vagrant/.bashrc
    state: present
    create: yes
    regexp: "^SSH_HOME="
    line: "SSH_HOME={{ beet_ssh_home }} && [ -e $SSH_HOME ] && cd $SSH_HOME"
  become: no
  when: beet_ssh_home is defined
