---
- name: Generate Drupal site with drush makefile.
  command: >
    {{ drush_path }} make -y {{ drupal_makefile_path }} --no-gitinfofile {% if drupal_distro %}--no-recursion{% endif %}
    chdir={{ beet_root }}
  when: not drupal_site.stat.exists

- name: Remove built distribution files/directories.
  file:
    path: "{{ beet_root }}/profiles/{{ drupal_distro }}/{{ item }}"
    state: absent
  with_items: "{% if drupal_distro %}{{ lookup('pipe', 'ls -A ' + beet_root + '/profiles/' + drupal_distro).split() }}{% endif %}"
  when: not drupal_site.stat.exists and drupal_distro

# @TODO - This makes an assumption of the root Vagrant share which is not yet
#         configurable. Make configurable and use variable.
- name: Symlink distribution files/directories.
  file:
    src: "../../../{{ item }}"
    dest: "{{ beet_root }}/profiles/{{ drupal_distro }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ lookup('pipe', 'ls -A ' + beet_base ).split() }}"
  when: not drupal_site.stat.exists and drupal_distro and item != 'docroot'

- name: Build distribution profile makefile.
  command: >
    {{ drush_path }} make -y {{ drupal_distro_makefile }} --no-gitinfofile --no-core --contrib-destination=./
    chdir={{ beet_root }}/profiles/{{ drupal_distro }}
  when: not drupal_site.stat.exists and drupal_distro
