---
purge_php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-intl
  - php-pear
  - php-apc
  - php7.0
  - libapache2-mod-php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - libpcre3-dev
__php7_packages:
  - php7.0
  - libapache2-mod-php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - libpcre3-dev
__php7_mysql_package: php7.0-mysql
__php7_fpm_daemon: php7.0-fpm
__php7_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"
