---
- name: Check if Drupal is already set up.
  stat: "path={{ beet_web }}/index.php"
  register: drupal_site

# Build makefile if configured.
- include: build-makefile.yml
  when: drupal_build_makefile and not drupal_build_composer
  become: no

# Build drupal composer if configured
- include: build-composer.yml
  when: drupal_build_composer and not drupal_build_makefile
  become: no

# Install site if configured.
- include: install-site.yml
  when: drupal_install_site
  become: no

- name: Generate drush login URL.
  command: >
    {{ drush_path }} --uri=http://{{ beet_domain }}/ user-login
    chdir={{ beet_root }}
  register: drupal_drush_login
  changed_when: false
  failed_when: false
